version: '3.9'

services:
  mycontacts-api:
    build: .
    container_name: mycontacts-api
    restart: always
    ports:
      - "3004:3004"
    links:
      - postgres
    networks:
      - mynetwork
    depends_on:
      - postgres

  postgres:
    image: postgres
    container_name: pg
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - '5432:5432'
    expose:
      - '5432'
    networks:
      - mynetwork
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

networks:
  mynetwork:
    driver: bridge